In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('karmanta_clean.csv')
df

,Employee_ID,Age,Attrition,Business_Travel,Sub-department,Distance_From_Home,Education,Environment_Satisfaction,Gender,Salary,...,Number_of_Companies_Worked_previously,Overtime,Salary_Hike_in_percent,Total_working_years_experience,Work_life_balance,No_of_years_worked_at_current_company,No_of_years_in_current_role,Years_since_last_promotion,Native_Place,External_experience
0,1,56.0,Yes,Travel Rarely,Network Administration,24,Graduation,5,Male,186630,...,7,Yes,85,9,1,7,2,4,Hyderabad,2
1,2,46.0,Yes,Travel Rarely,Software Development,45,Degree,5,Male,78553,...,3,No,22,18,4,1,2,0,Chennai,17
2,3,32.0,No,No Travel,Data Science,30,Master's,3,Female,175003,...,2,Yes,100,5,4,5,5,8,Lucknow,0
3,4,60.0,Yes,Travel Frequently,Data Science,42,Graduation,2,Female,100795,...,5,No,72,17,2,1,7,3,Lucknow,16
4,5,25.0,No,No Travel,Network Administration,26,Graduation,4,Female,75256,...,9,No,21,12,5,7,2,4,Lucknow,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9983,9996,33.0,Yes,Travel Frequently,Data Science,35,Degree,4,Male,108566,...,5,No,68,2,2,1,4,4,Hyderabad,1
9984,9997,62.0,No,Travel Rarely,Data Science,30,Degree,5,Female,115593,...,3,Yes,55,4,1,0,1,2,Chennai,4
9985,9998,32.0,No,Travel Rarely,Data Science,44,Degree,4,Female,160923,...,1,No,87,12,5,8,0,1,Jaipur,4
9986,9999,18.0,Yes,Travel Rarely,Data Science,46,Graduation,2,Male,163365,...,9,Yes,79,10,3,8,8,3,Bengaluru,2
9987,10000,39.0,Yes,No Travel,IT Services,1,Degree,1,Female,103537,...,2,Yes,34,4,3,2,2,3,Ahmedabad,2

In [4]:
df.isna().sum()

Employee_ID                              0
Age                                      0
Attrition                                0
Business_Travel                          0
Sub-department                           0
Distance_From_Home                       0
Education                                0
Environment_Satisfaction                 0
Gender                                   0
Salary                                   0
Job_Involvement                          0
Job_Level                                0
Job_Satisfaction                         0
Marital_Status                           0
Number_of_Companies_Worked_previously    0
Overtime                                 0
Salary_Hike_in_percent                   0
Total_working_years_experience           0
Work_life_balance                        0
No_of_years_worked_at_current_company    0
No_of_years_in_current_role              0
Years_since_last_promotion               0
Native_Place                             0
External_experience                      0
dtype: int64

In [5]:
df.dtypes

Employee_ID                                int64
Age                                      float64
Attrition                                 object
Business_Travel                           object
Sub-department                            object
Distance_From_Home                         int64
Education                                 object
Environment_Satisfaction                   int64
Gender                                    object
Salary                                     int64
Job_Involvement                            int64
Job_Level                                  int64
Job_Satisfaction                           int64
Marital_Status                            object
Number_of_Companies_Worked_previously      int64
Overtime                                  object
Salary_Hike_in_percent                     int64
Total_working_years_experience             int64
Work_life_balance                          int64
No_of_years_worked_at_current_company      int64
No_of_years_in_current_role                int64
Years_since_last_promotion                 int64
Native_Place                              object
External_experience                        int64
dtype: object

In [6]:
df.duplicated().sum()

0

In [7]:
num_cols = df.select_dtypes(include=["int64", "float64"]).columns

df[num_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
Employee_ID,9988.0,5002.582899,2885.826791,1.0,2504.75,5002.5,7501.25,10000.0
Age,9988.0,40.501302,13.160618,18.0,29.00,40.0,52.00,63.0
Distance_From_Home,9988.0,25.444734,14.389518,1.0,13.00,25.0,38.00,50.0
Environment_Satisfaction,9988.0,2.988086,1.414765,1.0,2.00,3.0,4.00,5.0
Salary,9988.0,114514.475070,49020.692168,30078.0,72133.50,114544.0,157285.75,199989.0
Job_Involvement,9988.0,2.985983,1.423319,1.0,2.00,3.0,4.00,5.0
Job_Level,9988.0,4.531237,2.286202,1.0,3.00,5.0,7.00,8.0
Job_Satisfaction,9988.0,2.990989,1.427294,1.0,2.00,3.0,4.00,5.0
Number_of_Companies_Worked_previously,9988.0,5.010112,3.166707,0.0,2.00,5.0,8.00,10.0
Salary_Hike_in_percent,9988.0,50.155487,29.157273,0.0,25.00,51.0,75.00,100.0
Total_working_years_experience,9988.0,10.933020,5.176046,0.0,7.00,10.0,15.00,20.0
Work_life_balance,9988.0,3.003104,1.412971,1.0,2.00,3.0,4.00,5.0
No_of_years_worked_at_current_company,9988.0,4.978674,3.177636,0.0,2.00,5.0,8.00,10.0
No_of_years_in_current_role,9988.0,5.003404,3.148249,0.0,2.00,5.0,8.00,10.0
Years_since_last_promotion,9988.0,3.986284,2.587666,0.0,2.00,4.0,6.00,8.0
External_experience,9988.0,5.954345,5.577415,0.0,0.00,5.0,10.00,20.0

In [8]:
cat_cols = df.select_dtypes(include=["object"]).columns

for col in cat_cols:
    print("\n", col)
    print(df[col].value_counts())

 Attrition
Attrition
No     7743
Yes    2245
Name: count, dtype: int64

 Business_Travel
Business_Travel
Travel Rarely        5980
Travel Frequently    2012
No Travel            1996
Name: count, dtype: int64

 Sub-department
Sub-department
Cyber Security            2078
Software Development      2063
Data Science              1954
IT Services               1954
Network Administration    1939
Name: count, dtype: int64

 Education
Education
Graduation       3063
Degree           2988
Master's         1987
PhD               978
Below College     972
Name: count, dtype: int64

 Gender
Gender
Female    5022
Male      4966
Name: count, dtype: int64

 Marital_Status
Marital_Status
Married     3387
Divorced    3350
Single      3251
Name: count, dtype: int64

 Overtime
Overtime
No     6939
Yes    3049
Name: count, dtype: int64

 Native_Place
Native_Place
Jaipur       1048
Delhi        1037
Bengaluru    1027
Mumbai       1020
Ahmedabad    1017
Lucknow      1002
Pune          996
Hyderabad     964
Kolkata       948
Chennai       929
Name: count, dtype: int64

## Demographic Analysis & Overall Stats

In [9]:
df["Attrition"].value_counts(normalize=True)["Yes"] * 100

22.476972366840208

In [10]:
pd.DataFrame(df["Attrition"].value_counts(normalize=True) * 100)

           proportion
Attrition
No          77.523028
Yes         22.476972

In [11]:
pd.crosstab(df["Native_Place"], df["Attrition"], normalize="index") * 100

Attrition            No        Yes
Native_Place
Ahmedabad     75.319567  24.680433
Bengaluru     78.773126  21.226874
Chennai       76.318622  23.681378
Delhi         78.206365  21.793635
Hyderabad     78.941909  21.058091
Jaipur        76.908397  23.091603
Kolkata       77.320675  22.679325
Lucknow       77.944112  22.055888
Mumbai        78.333333  21.666667
Pune          77.108434  22.891566

In [12]:
pd.crosstab(df["Gender"], df["Attrition"], normalize="index") * 100

Attrition         No        Yes
Gender
Female     77.618479  22.381521
Male       77.426500  22.573500

In [13]:
pd.crosstab(df["Marital_Status"], df["Attrition"], normalize="index") * 100

Attrition              No        Yes
Marital_Status
Divorced        78.447761  21.552239
Married         77.384116  22.615884
Single          76.714857  23.285143

## Burnout & Education Impact

In [14]:
pd.crosstab(df["Overtime"], df["Attrition"], normalize="index") * 100

Attrition         No        Yes
Overtime
No         79.132440  20.867560
Yes        73.860282  26.139718

In [15]:
pd.crosstab(df["Education"], df["Attrition"], normalize="index") * 100

Attrition             No        Yes
Education
Below College  79.423868  20.576132
Degree         77.108434  22.891566
Graduation     77.081293  22.918707
Master's       77.956719  22.043281
PhD            77.402863  22.597137

## Growth Stagnation

In [16]:
pd.DataFrame(df.groupby("Attrition")["Years_since_last_promotion"].mean())

           Years_since_last_promotion
Attrition
No                           3.814930
Yes                          4.577283

In [17]:
pd.DataFrame(df.groupby("Attrition")["No_of_years_in_current_role"].mean())

           No_of_years_in_current_role
Attrition
No                            5.021697
Yes                           4.940312

## Satisfaction Metrics

In [18]:
df.groupby("Attrition")[
    ["Job_Satisfaction","Environment_Satisfaction","Work_life_balance"]
].mean()

           Job_Satisfaction  Environment_Satisfaction  Work_life_balance
Attrition
No                 3.054501                  3.136769           3.117138
Yes                2.771938                  2.475278           2.609800

## Pay & Compensation

In [19]:
pd.DataFrame(df.groupby("Attrition")["Salary"].mean())

                  Salary
Attrition
No         114435.910371
Yes        114785.444543

In [20]:
pd.DataFrame(df.groupby("Attrition")["Salary_Hike_in_percent"].mean())

           Salary_Hike_in_percent
Attrition
No                      50.025571
Yes                     50.603563

## Career Stage Analysis

In [21]:
df["age_band"] = pd.cut(
    df["Age"],
    bins=[18, 25, 35, 45, 55, 65]
)

pd.crosstab(df["age_band"], df["Attrition"], normalize="index") * 100

Attrition         No        Yes
age_band
(18, 25]   77.306397  22.693603
(25, 35]   77.762681  22.237319
(35, 45]   76.871358  23.128642
(45, 55]   77.122970  22.877030
(55, 65]   78.558875  21.441125

## Structural Metrics

In [22]:
pd.crosstab(df["Job_Level"], df["Attrition"], normalize="index") * 100

Attrition         No        Yes
Job_Level
1          76.265560  23.734440
2          79.681275  20.318725
3          78.293289  21.706711
4          78.463975  21.536025
5          76.168224  23.831776
6          76.375405  23.624595
7          78.267717  21.732283
8          76.656151  23.343849

In [23]:
pd.crosstab(df["Sub-department"], df["Attrition"], normalize="index") * 100

Attrition                      No        Yes
Sub-department
Cyber Security          75.842156  24.157844
Data Science            77.379734  22.620266
IT Services             78.045036  21.954964
Network Administration  78.855080  21.144920
Software Development    77.605429  22.394571

## Distance & Travel Impact

In [24]:
df["distance_band"] = pd.cut(
    df["Distance_From_Home"],
    bins=[0,10,20,30,40,50]
)

pd.crosstab(df["distance_band"], df["Attrition"], normalize="index") * 100

Attrition             No        Yes
distance_band
(0, 10]        91.404298   8.595702
(10, 20]       75.435005  24.564995
(20, 30]       75.772201  24.227799
(30, 40]       74.774323  25.225677
(40, 50]       70.106762  29.893238

In [25]:
pd.crosstab(df["Business_Travel"], df["Attrition"], normalize="index") * 100

Attrition                 No        Yes
Business_Travel
No Travel          81.262525  18.737475
Travel Frequently  65.755467  34.244533
Travel Rarely      80.234114  19.765886

## Experience Metrics

In [26]:
pd.crosstab(
    pd.cut(df["External_experience"], bins=[0,2,5,10,20]),
    df["Attrition"],
    normalize="index"
) * 100

Attrition                   No        Yes
External_experience
(0, 2]               74.836601  25.163399
(2, 5]               76.739283  23.260717
(5, 10]              76.880578  23.119422
(10, 20]             79.041667  20.958333

In [27]:
pd.crosstab(
    pd.cut(df["No_of_years_worked_at_current_company"], bins=[0,2,5,10,20]),
    df["Attrition"],
    normalize="index"
) * 100

Attrition                                     No        Yes
No_of_years_worked_at_current_company
(0, 2]                                 76.864035  23.135965
(2, 5]                                 78.192462  21.807538
(5, 10]                                77.456647  22.543353

In [28]:
pd.DataFrame(df.groupby("Attrition")["Job_Involvement"].mean())

           Job_Involvement
Attrition
No                3.109518
Yes               2.559911

In [29]:
pd.crosstab(
    pd.cut(df["Number_of_Companies_Worked_previously"], bins=[0,2,5,10]),
    df["Attrition"],
    normalize="index"
) * 100

Attrition                                     No        Yes
Number_of_Companies_Worked_previously
(0, 2]                                 77.511416  22.488584
(2, 5]                                 78.683158  21.316842
(5, 10]                                76.970498  23.029502

In [30]:
pd.crosstab(
    pd.cut(df["Total_working_years_experience"], bins=[0,5,10,20]),
    df["Attrition"],
    normalize="index"
) * 100

Attrition                              No        Yes
Total_working_years_experience
(0, 5]                          77.148313  22.851687
(5, 10]                         77.299250  22.700750
(10, 20]                        77.889658  22.110342